# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradepredict', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.AlterField(
            model_name='input',
            name='csvstr',
            field=models.TextField(null=True, verbose_name='CSV record for all test grades:'),
        ),
    ]
