# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradepredict', '0002_auto_20171121_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='csvfile',
            field=models.FileField(null=True, upload_to='documents/', verbose_name='Upload your CSV file:'),
        ),
    ]
