# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradepredict', '0003_input_csvfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AlterField(
            model_name='input',
            name='csvfile',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Upload your CSV file:'),
        ),
        migrations.AlterField(
            model_name='input',
            name='csvstr',
            field=models.TextField(blank=True, null=True, verbose_name='CSV record for all test grades:'),
        ),
    ]
